export const routes = [
    {
        id: 1,
        from: "Bến Thành",
        to: "Bến Xe Buýt Chợ Lớn",
        start: "05:05",
        end: "18:15",
        route: "01",
        interval: "10p - 20p",
        price: "7,000",
        stuPrice: "3,000",
        type: "Phổ thông - Có trợ giá",
        times: 120
    },
    {
        id: 2,
        from: "Bến Thành",
        to: "Suối Tiên",
        start: "15:30",
        end: "22:30",
        route: "02",
        interval: "8p - 15p",
        price: "7,000",
        stuPrice: "3,000",
        type: "Phổ thông - Có trợ giá",
        times: 98
    },
    {
        id: 3,
        from: "Bến Thành",
        to: "Suối Tiên",
        start: "15:30",
        end: "22:30",
        route: "03",
        interval: "8p - 15p",
        price: "7,000",
        stuPrice: "3,000",
        type: "Phổ thông - Có trợ giá",
        times: 86
    },
    {
        id: 4,
        from: "Bến Thành",
        to: "Suối Tiên",
        start: "18:30",
        end: "22:30",
        route: "04",
        interval: "8p - 15p",
        price: "7,000",
        stuPrice: "3,000",
        type: "Phổ thông - Có trợ giá",
        times: 86
    },
    {
        id: 5,
        from: "Bến Thành",
        to: "Suối Tiên",
        start: "18:30",
        end: "22:30",
        route: "05",
        interval: "8p - 15p",
        price: "7,000",
        stuPrice: "3,000",
        type: "Phổ thông - Có trợ giá",
        times: 86
    }, 
    {
        id: 6, 
        from: "Bến Thành",
        to: "Suối Tiên",
        start: "15:30",
        end: "22:30",
        route: "06",
        interval: "8p - 15p",
        price: "7,000",
        stuPrice: "3,000",
        type: "Phổ thông - Có trợ giá",
        times: 86
    },
    {
        id: 7,
        from: "Bến Thành",
        to: "Suối Tiên",
        start: "15:30",
        end: "22:30",
        route: "07",
        interval: "8p - 15p",
        price: "7,000",
        stuPrice: "3,000",
        type: "Phổ thông - Có trợ giá",
        times: 86
    }, 
    {
        id: 8,
        from: "Bến Thành",
        to: "Suối Tiên",
        start: "15:30",
        end: "22:30",
        route: "08",
        interval: "8p - 15p",
        price: "7,000",
        stuPrice: "3,000",
        type: "Phổ thông - Có trợ giá",
        times: 86
    }, 
    {
        id: 9,
        from: "Bến Thành",
        to: "Suối Tiên",
        start: "05:30",
        end: "17:30",
        route: "09",
        interval: "8p - 15p",
        price: "7,000",
        stuPrice: "3,000",
        type: "Phổ thông - Có trợ giá",
        times: 86
    },
    {
        id: 10,
        from: "Bến Thành",
        to: "Suối Tiên",
        start: "15:30",
        end: "22:30",
        route: "10",
        interval: "8p - 15p",
        price: "7,000",
        stuPrice: "3,000",
        type: "Phổ thông - Có trợ giá",
        times: 86
    },
    {
        id: "11",
        from: "Bến Thành",
        to: "Suối Tiên",
        start: "05:30",
        end: "18:30",
        route: 11,
        interval: "8p - 15p",
        price: "7,000",
        stuPrice: "3,000",
        type: "Phổ thông - Có trợ giá",
        times: 86
    },
    {
        id: "12",
        from: "Bến Thành",
        to: "Suối Tiên",
        start: "05:30",
        end: "18:30",
        route: 11,
        interval: "8p - 15p",
        price: "7,000",
        stuPrice: "3,000",
        type: "Phổ thông - Có trợ giá",
        times: 86
    }
];

export const busStops = [
    "Bến Thành",
    "Công trường Mê Linh",
    "Bến Bạch Đằng",
    "Cục Hải quan Thành phố",
    "Trường Cao Thắng",
    "Bảo tàng Mỹ Thuật",
    "KTX Trần Hưng Đạo",
    "Rạp Hưng Đạo",
    "Nguyễn Biểu",
    "Bệnh viện Chấn thương Chỉnh hình",
    "Rạp Đồng Tháp",
    "Rạp Đống Đa",
    "Nhà Văn hoá Quận 5",
    "Triệu Quang Phục",
    "Hải Thượng Lãn Ông",
    "Bến Xe Buýt Chợ Lớn",
    "Nhà hát Thành phố",
    "Ba Son",
    "Văn Thánh",
    "Cầu Sài Gòn",
    "An Phú",
    "Rạch Chiếc",
    "Thủ Đức",
    "Trường mầm non Vành Khuyên",
    "Làng Thiếu niên Thủ Đức",
    "Ngã ba Chương Dương",
    "Cao đẳng xây dựng 2",
    "Siêu thị Nguyễn Kim",
    "Trạm Hutech - Khu Công nghệ cao",
    "Đại học Nông Lâm",
    "Bến xe Miền Đông Mới",
    "Suối Tiên",
];